target-version = "py311"

[lint]
select = ["E", "I", "N", "PL"]
fixable = ["ALL"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
